spring:
  config:
    activate:
      on-profile: deploy
  devtools:
    add-properties: false

  jpa: # https://www.zhangbj.com/p/1411.html https://blog.csdn.net/zhaolinfenggg/article/details/135706459
    show-sql: false # 显示sql
    hibernate: # 自动生成表结构
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  datasource:
    dynamic:
      primary: train #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      lazy: true
      datasource:
        train:
          url: jdbc:mysql://10.8.54.24:3306/train?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    redis:  # Redis
#      host: localhost
#      port: 6379

server:
  port: 8090

minio: # https://mp.weixin.qq.com/s/ptlGsr0OJZ1g4ehY-MUEdA
  config:
    # 这里配置的url,user, password必须都是在cmd中运行minio的api栏的数据，否则会导致文件上传失败，判断文件是否存在失败，文件下载失败
    url: http://localhost:9000 # ip地址 webUI地址：http://host.docker.internal:4833
    accessKey: minioadmin # 账号
    secretKey: minioadmin # 密码
    secure: false # 如果是true，则用的是https而不是http,默认值是true
    bucketName: "train"  # 桶的名字 相当于文件夹

logging:
  level:
    # root: debug # 指定日志级别 把springboot的所有日志修改成为debug
    # web: trace # 打印servlet相关的信息

# 参考开源yudao项目
# https://springdoc.org/#properties
# https://github.com/swagger-api/swagger-ui
# https://springdoc.cn/spring-rest-openapi-documentation/
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs # 如何访问api: http://localhost:8092/v3/api-docs
    version: OPENAPI_3_1
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

smlj-x:
  clearWhenServerOn: true